toy-car-project-lwc/force-app/main/default/objects/Car_Manufacturer__c/Car_Manufacturer__c.object-meta.xml
<CustomObject>
    <label>Car Manufacturer</label>
    <nameField>
        <displayFormat>CM-{00}</displayFormat>
        <label>Car Manufacturer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

toy-car-project-lwc/force-app/main/default/objects/Car_Manufacturer__c/fields/Car_Manufacturer_Name__c.field-meta.xml
<CustomField>
    <fullName>Car_Manufacturer_Name__c</fullName>
    <label>Car Manufacturer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/Toy_Car__c.object-meta.xml
<CustomObject>
    <label>Toy Car</label>
    <nameField>
        <displayFormat>TC-{000}</displayFormat>
        <label>Toy Car ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toy Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/fields/Car_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Car_Manufacturer__c</fullName>
    <label>Car Manufacturer</label>
    <referenceTo>Car_Manufacturer__c</referenceTo>
    <relationshipLabel>Toy Cars</relationshipLabel>
    <relationshipName>Toy_Cars</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/fields/Car_Year__c.field-meta.xml
<CustomField>
    <fullName>Car_Year__c</fullName>
    <label>Car Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/fields/Toy_Car_Name__c.field-meta.xml
<CustomField>
    <fullName>Toy_Car_Name__c</fullName>
    <label>Toy Car Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/fields/Toy_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Toy_Manufacturer__c</fullName>
    <label>Toy Manufacturer</label>
    <referenceTo>Toy_Manufacturer__c</referenceTo>
    <relationshipLabel>Toy Cars</relationshipLabel>
    <relationshipName>Toy_Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Car__c/fields/Toy_Year__c.field-meta.xml
<CustomField>
    <fullName>Toy_Year__c</fullName>
    <label>Toy Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/objects/Toy_Manufacturer__c/Toy_Manufacturer__c.object-meta.xml
<CustomObject>
    <label>Toy Manufacturer</label>
    <nameField>
        <displayFormat>TM-{00}</displayFormat>
        <label>Toy Manufacturer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toy Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

toy-car-project-lwc/force-app/main/default/objects/Toy_Manufacturer__c/fields/Toy_Manufacturer_Name__c.field-meta.xml
<CustomField>
    <fullName>Toy_Manufacturer_Name__c</fullName>
    <label>Toy Manufacturer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

toy-car-project-lwc/force-app/main/default/classes/ToyCarController.cls
public with sharing class ToyCarController {
    
    public class ToyCarWrapper {
        @AuraEnabled 
        public Id toyCarId;
        @AuraEnabled 
        public String carManufacturerName;
        @AuraEnabled
        public Decimal carYear;
        @AuraEnabled
        public String toyCarName;
        @AuraEnabled
        public String toyManufacturerName;
        @AuraEnabled
        public String color;
        @AuraEnabled
        public String variant;
        @AuraEnabled
        public String photoUrl;
    }    

    private static String getRecordAttachments(Id toyCarId){
        try {          
            String contentVersionId = '', contentDocumentLinkId = '';              
            // List<ContentDocumentLink> contentDocumentLinkList = 
            // [SELECT Id, LinkedEntityId, ContentDocumentId, Visibility, IsDeleted, ShareType, ContentDocument.Title, ContentDocument.createdDate FROM ContentDocumentLink WHERE LinkedEntityId IN :setToyCarIds];
            List<ContentDocumentLink> contentDocumentLinkList = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :toyCarId LIMIT 1];
            // System.debug('ToyCarController getRecordAttachments contentDocumentLinkList debug: '+contentDocumentLinkList);
            if(contentDocumentLinkList.size() > 0) {
                contentDocumentLinkId = contentDocumentLinkList[0].Id;
                // System.debug('ToyCarController getRecordAttachments contentDocumentLink debug: '+contentDocumentLink);
                List<ContentVersion> contentVersionIdList = [SELECT Id, Title FROM ContentVersion WHERE ContentDocumentId = :contentDocumentLinkList[0].ContentDocumentId LIMIT 1];
                // System.debug('ToyCarController getRecordAttachments contentVersionIdList debug: '+contentVersionIdList);
                if(contentVersionIdList.size() > 0) {
                    contentVersionId = contentVersionIdList[0].Id;
                    // System.debug('ToyCarController getRecordAttachments contentVersionId debug: '+contentVersionId);
                }
            }            
            return contentVersionId;                
        } catch (Exception ex) {
            System.debug('Exception in getRecordAttachments: ' + ex + ', Cause: ' + ex.getCause() + ', Line number: ' + ex.getLineNumber() + ', Message: ' + ex.getMessage() + ', Get stack trace: ' + ex.getStackTraceString() + ', Get type: ' + ex.getTypeName());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static List<ToyCarWrapper> getToyCarsList() {
        try {
            List<ToyCarWrapper> toyCarWrapperList = new List<ToyCarWrapper>();                                   
            ToyCarWrapper toyCarWrapperObj;
            for(Toy_Car__c toyCar: [
                SELECT 
                Id, 
                Car_Manufacturer__c,
                Car_Year__c,
                Color__c,
                Name,
                Toy_Car_Name__c,
                Toy_Manufacturer__r.Toy_Manufacturer_Name__c,
                Toy_Year__c,
                Car_Manufacturer__r.Car_Manufacturer_Name__c,
                Variant__c,
                Pack__c
                FROM Toy_Car__c
                ORDER BY Car_Manufacturer__r.Car_Manufacturer_Name__c]) {
                    toyCarWrapperObj = new ToyCarWrapper();
                    toyCarWrapperObj.toyCarId = toyCar.Id;
                    toyCarWrapperObj.carManufacturerName = toyCar.Car_Manufacturer__r.Car_Manufacturer_Name__c;
                    toyCarWrapperObj.carYear = toyCar.Car_Year__c;
                    toyCarWrapperObj.toyCarName = toyCar.Toy_Car_Name__c;
                    toyCarWrapperObj.toyManufacturerName = toyCar.Toy_Manufacturer__r.Toy_Manufacturer_Name__c;
                    toyCarWrapperObj.color = toyCar.Color__c;
                    toyCarWrapperObj.variant = toyCar.Variant__c;
                    toyCarWrapperObj.photoUrl = getRecordAttachments(toyCar.Id);
                    toyCarWrapperList.add(toyCarWrapperObj);
                }

            if(toyCarWrapperList.size()>0) {
                return toyCarWrapperList;
            } else {
                return new List<ToyCarWrapper>();
            }
        } catch (Exception ex) {
            System.debug('Exception in getRecordAttachments: ' + ex + ', Cause: ' + ex.getCause() + ', Line number: ' + ex.getLineNumber() + ', Message: ' + ex.getMessage() + ', Get stack trace: ' + ex.getStackTraceString() + ', Get type: ' + ex.getTypeName());
            throw new AuraHandledException(ex.getMessage());            
        }
    }

}